GET http://localhost:5000/api/types

###

GET http://localhost:5000/api/types/66b9804945c346146bf30305

###

POST http://localhost:5000/api/types
Content-Type: application/json

{
    "name": "Тест"
}

###

PUT http://localhost:5000/api/types
Content-Type: application/json

{
    "_id": "66bc01fab000d154fb70c855",
    "name": "Обновленный"
}

###

DELETE http://localhost:5000/api/types/66bc021a89a18e0186a65796